### ISSUE TITLE
Replace to English

### ISSUE THREAD

**Issue by vicentequintero** [danila-shirkov/exercises-python#14]
https://github.com/danila-shirkov/exercises-python/blob/09765b9896a8251958df5795855d448ba9de753a/exercises-python_all_link.txt#L191C4-L191C4

https://en.wikipedia.org/wiki/Pure_function

**Comment by yana-fesenko** [comment]
@vicentequintero почему на англ?в оригинале на исп, надо найти на испанском

**Comment by vicentequintero** [comment]
No hay una página para funciones puras en Wikipedia en español.

Aquí son mencionadas en una sección, pero hasta ahí:

https://es.wikipedia.org/wiki/Programación_funcional

**Comment by yana-fesenko** [comment]
@vicentequintero ok, dejemos esta https://en.wikipedia.org/wiki/Pure_function. Por favor cierra el issue cuando cambias el enlace
