### ISSUE TITLE
Русский текст

### ISSUE THREAD

**Issue by danila-shirkov** [danila-shirkov/exercises-python#7]
https://github.com/danila-shirkov/exercises-python/blob/c8f9a5fd96a9fdd4f1353190184ec85055899faa/modules/50-loops/20-aggregation-numbers/description.es.yml#L53

**Comment by danila-shirkov** [comment]
@vicentequintero @yana-fesenko info

**Comment by yana-fesenko** [comment]
@danila-shirkov все ок, поняла

**Comment by yana-fesenko** [comment]
@vicentequintero Висенте, в переводе на испанский присутствует русский текст, надо исправить на испанский, спасибо

**Comment by vicentequintero** [comment]
Quedó solucionado @yana-fesenko
