### ISSUE TITLE
Русский текст

### ISSUE THREAD

**Issue by danila-shirkov** [danila-shirkov/exercises-python#8]
https://github.com/danila-shirkov/exercises-python/blob/c8f9a5fd96a9fdd4f1353190184ec85055899faa/modules/48-conditionals/65-match/description.es.yml#L58-L61

**Comment by danila-shirkov** [comment]
@yana-fesenko @vicentequintero

**Comment by yana-fesenko** [comment]
@vicentequintero посмотри, пожалуйста

**Comment by vicentequintero** [comment]
Quedó solucionado @yana-fesenko
